name: Compile ISO draft
description: "Build an ISO .docx file from markdown input"
inputs:
  md-in:
    description: "Markdown input file"
    required: true
  docx-out:
    description: "Docx output file"
    required: true
runs:
  using: docker
  image: docker://ghcr.io/matthiasvalvekens/pandoc-iso:1.0.0
  args:
    - ${{ inputs.md-in }}
    - ${{ inputs.docx-out }}
