name: Compile ISO draft
description: "Build an ISO .docx file from markdown input"
inputs:
  md-in:
    description: "Markdown input file"
    required: true
  docx-out:
    description: "Docx output file"
    required: true
branding:
  icon: globe
  color: blue
runs:
  using: docker
  image: docker://ghcr.io/matthiasvalvekens/pandoc-iso:latest
  args:
    - ${{ inputs.md-in }}
    - ${{ inputs.docx-out }}
