name:                pandoc-iso
version:             0.2.0.0
author:              "Matthias Valvekens"
maintainer:          "dev@mvalvekens.be"
copyright:           "2021 Matthias Valvekens"

description:         Pandoc-based utils for ISO document formatting

dependencies:
- base >= 4.7 && < 5
- hashable >= 1.3
- unordered-containers >= 0.2.13.0
- mtl >= 2.2.2
- text >= 1.2.4.1
- pandoc-types >= 1.22
- lens >= 5 && <6
- containers >= 0.6.2.1
- file-embed >= 0.0.15.0
- attoparsec  # implicit dependencies through aeson, but we need it

library:
  source-dirs: src
  ghc-options:
  - -Wall
  exposed-modules:
    - Text.Pandoc.ISO.Filter

executables:
  pandoc-iso:
    dependencies:
      - pandoc-iso
    main: PandocISO.hs
    source-dirs: app
    ghc-options:
      - -Wall
